In [1]:
import scipy.linalg

In [5]:
A = scipy.array([[1, 2, 3,4],
             [4, 5, 6,7],
             [10, 11, 9,8],
             [12,13,15,14]])
print(A)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [10 11  9  8]
 [12 13 15 14]]


<ipython-input-5-1c1790f48fee>:1: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  A = scipy.array([[1, 2, 3,4],


In [6]:
P, L, U = scipy.linalg.lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
[[1.         0.         0.         0.        ]
 [0.08333333 1.         0.         0.        ]
 [0.83333333 0.18181818 1.         0.        ]
 [0.33333333 0.72727273 0.07142857 1.        ]]
[[12.         13.         15.         14.        ]
 [ 0.          0.91666667  1.75        2.83333333]
 [ 0.          0.         -3.81818182 -4.18181818]
 [ 0.          0.          0.          0.57142857]]
