In [2]:
import pprint
import scipy
import scipy.linalg

In [3]:
A = scipy.array([[1, 1, 1], [0, 1, 0], [0, 1, 1]])  # From the Wikipedia Article on QR Decomposition

<ipython-input-3-46569df2b9f7>:1: DeprecationWarning: scipy.array is deprecated and will be removed in SciPy 2.0.0, use numpy.array instead
  A = scipy.array([[1, 1, 1], [0, 1, 0], [0, 1, 1]])  # From the Wikipedia Article on QR Decomposition


In [4]:
Q, R = scipy.linalg.qr(A)

In [5]:
print ("A:")
pprint.pprint(A)

A:
array([[1, 1, 1],
       [0, 1, 0],
       [0, 1, 1]])


In [6]:
print ("Q:")
pprint.pprint(Q)

Q:
array([[ 1.        ,  0.        ,  0.        ],
       [-0.        , -0.70710678, -0.70710678],
       [-0.        , -0.70710678,  0.70710678]])


In [7]:
print ("R:")
pprint.pprint(R)

R:
array([[ 1.        ,  1.        ,  1.        ],
       [ 0.        , -1.41421356, -0.70710678],
       [ 0.        ,  0.        ,  0.70710678]])
